// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line tpl/layout.qtpl:1
package tpl

//line tpl/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tpl/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tpl/layout.qtpl:2
type Page interface {
//line tpl/layout.qtpl:2
	Domain() string
//line tpl/layout.qtpl:2
	StreamDomain(qw422016 *qt422016.Writer)
//line tpl/layout.qtpl:2
	WriteDomain(qq422016 qtio422016.Writer)
//line tpl/layout.qtpl:2
	Title() string
//line tpl/layout.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line tpl/layout.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line tpl/layout.qtpl:2
	Body() string
//line tpl/layout.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line tpl/layout.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line tpl/layout.qtpl:2
	CSS() string
//line tpl/layout.qtpl:2
	StreamCSS(qw422016 *qt422016.Writer)
//line tpl/layout.qtpl:2
	WriteCSS(qq422016 qtio422016.Writer)
//line tpl/layout.qtpl:2
	JS() string
//line tpl/layout.qtpl:2
	StreamJS(qw422016 *qt422016.Writer)
//line tpl/layout.qtpl:2
	WriteJS(qq422016 qtio422016.Writer)
//line tpl/layout.qtpl:2
}

//line tpl/layout.qtpl:11
func StreamLayout(qw422016 *qt422016.Writer, p Page) {
//line tpl/layout.qtpl:11
	qw422016.N().S(`
<html lang="ru">
	<head>
		<title>`)
//line tpl/layout.qtpl:14
	p.StreamTitle(qw422016)
//line tpl/layout.qtpl:14
	qw422016.N().S(`</title>
		<style>`)
//line tpl/layout.qtpl:15
	qw422016.N().S(`body {
    font-family: Arial, sans-serif;
}

* {
    box-sizing: border-box;
}

#container {
    max-width: 1000px;
    margin: 0 auto;
}

#form > div {
    margin-bottom: 1em;
}

#form > div label {
    display: block;
    margin-bottom: 4px;
}

#error {
    color: red;
    padding: 10px;
    margin: 10px 0;
    border: 1px solid red;
    border-radius: 6px;
}

#error:empty {
    display: none;
}

button, .btn {
    box-shadow: inset 0 1px 0 0 #f9eca0;
    background: #f0c911 linear-gradient(to bottom, #f0c911 5%, #f2ab1e 100%);
    border-radius: 6px;
    border: 1px solid #e65f44;
    display: inline-block;
    cursor: pointer;
    color: #c92200;
    font-family: Arial, sans-serif;
    font-size: 15px;
    font-weight: bold;
    padding: 6px 24px;
    text-decoration: none;
    text-shadow: 0 1px 0 #ded17c;
}

button:hover, .btn:hover {
    background: #f2ab1e linear-gradient(to bottom, #f2ab1e 5%, #f0c911 100%);
}

button:active, .btn:active {
    position: relative;
    top: 1px;
}

input, select {
    outline: none;
    width: 100%;
    display: inline-block;
    /*-webkit-box-sizing: content-box;*/
    /*-moz-box-sizing: content-box;*/
    box-sizing: border-box;
    padding: 10px 20px;
    border: 1px solid #b7b7b7;
    /*-webkit-border-radius: 3px;*/
    border-radius: 3px;
    font: normal 16px/normal Arial, sans-serif;
    color: #333; /*rgba(0, 142, 198, 1);*/
    /*-o-text-overflow: clip;*/
    text-overflow: clip;
    background: rgba(252, 252, 252, 1);
    /*-webkit-box-shadow: 2px 2px 2px 0 rgba(0, 0, 0, 0.2) inset;*/
    box-shadow: 2px 2px 2px 0 rgba(0, 0, 0, 0.2) inset;
    text-shadow: 1px 1px 0 rgba(255, 255, 255, 0.66);
    /*-webkit-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);*/
    /*-moz-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);*/
    /*-o-transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);*/
    transition: all 200ms cubic-bezier(0.42, 0, 0.58, 1);
}
`)
//line tpl/layout.qtpl:15
	qw422016.N().S(`</style>
		`)
//line tpl/layout.qtpl:16
	p.StreamCSS(qw422016)
//line tpl/layout.qtpl:16
	qw422016.N().S(`
		<script>const sessionDomain = '`)
//line tpl/layout.qtpl:17
	p.StreamDomain(qw422016)
//line tpl/layout.qtpl:17
	qw422016.N().S(`';</script>
		<script>`)
//line tpl/layout.qtpl:18
	qw422016.N().S(`const api = (() => {

    const req = async (method, path, data) => {
        let body;
        if (data) {
            body = JSON.stringify(data);
        }
        const res = await fetch(path, {
            method,
            body,
            credentials: 'include',
            headers: {
                'content-type': 'application/json',
            },
        });
        const json = await res.json();
        if (res.status !== 200) {
            throw new Error(json.message);
        }
        return json;
    };

    return {
        get: (path) => req('GET', path),
        post: (path, data) => req('POST', path, data),
    };

})();

const gid = (id) => document.getElementById(id);

const setDisabled = (disabled, ...elements) => elements.forEach(e => e.disabled = disabled);

const redirect = () => {
    location.href = `)
//line tpl/layout.qtpl:18
	qw422016.N().S("`")
//line tpl/layout.qtpl:18
	qw422016.N().S(`${location.protocol}//${sessionDomain}${location.port ? `)
//line tpl/layout.qtpl:18
	qw422016.N().S("`")
//line tpl/layout.qtpl:18
	qw422016.N().S(`:${location.port}`)
//line tpl/layout.qtpl:18
	qw422016.N().S("`")
//line tpl/layout.qtpl:18
	qw422016.N().S(` : ''}`)
//line tpl/layout.qtpl:18
	qw422016.N().S("`")
//line tpl/layout.qtpl:18
	qw422016.N().S(`;
};`)
//line tpl/layout.qtpl:18
	qw422016.N().S(`</script>
	</head>
	<body>
	    <main id="container">
		    `)
//line tpl/layout.qtpl:22
	p.StreamBody(qw422016)
//line tpl/layout.qtpl:22
	qw422016.N().S(`
		</main>
		`)
//line tpl/layout.qtpl:24
	p.StreamJS(qw422016)
//line tpl/layout.qtpl:24
	qw422016.N().S(`
	</body>
</html>
`)
//line tpl/layout.qtpl:27
}

//line tpl/layout.qtpl:27
func WriteLayout(qq422016 qtio422016.Writer, p Page) {
//line tpl/layout.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:27
	StreamLayout(qw422016, p)
//line tpl/layout.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:27
}

//line tpl/layout.qtpl:27
func Layout(p Page) string {
//line tpl/layout.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:27
	WriteLayout(qb422016, p)
//line tpl/layout.qtpl:27
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:27
	return qs422016
//line tpl/layout.qtpl:27
}

//line tpl/layout.qtpl:29
type BasePage struct {
	SessionDomain string
}

//line tpl/layout.qtpl:32
func (p *BasePage) StreamDomain(qw422016 *qt422016.Writer) {
//line tpl/layout.qtpl:32
	qw422016.E().S(p.SessionDomain)
//line tpl/layout.qtpl:32
}

//line tpl/layout.qtpl:32
func (p *BasePage) WriteDomain(qq422016 qtio422016.Writer) {
//line tpl/layout.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:32
	p.StreamDomain(qw422016)
//line tpl/layout.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:32
}

//line tpl/layout.qtpl:32
func (p *BasePage) Domain() string {
//line tpl/layout.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:32
	p.WriteDomain(qb422016)
//line tpl/layout.qtpl:32
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:32
	return qs422016
//line tpl/layout.qtpl:32
}

//line tpl/layout.qtpl:33
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line tpl/layout.qtpl:33
	qw422016.N().S(`This is a base title`)
//line tpl/layout.qtpl:33
}

//line tpl/layout.qtpl:33
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line tpl/layout.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:33
	p.StreamTitle(qw422016)
//line tpl/layout.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:33
}

//line tpl/layout.qtpl:33
func (p *BasePage) Title() string {
//line tpl/layout.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:33
	p.WriteTitle(qb422016)
//line tpl/layout.qtpl:33
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:33
	return qs422016
//line tpl/layout.qtpl:33
}

//line tpl/layout.qtpl:34
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line tpl/layout.qtpl:34
	qw422016.N().S(`This is a base body`)
//line tpl/layout.qtpl:34
}

//line tpl/layout.qtpl:34
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line tpl/layout.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:34
	p.StreamBody(qw422016)
//line tpl/layout.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:34
}

//line tpl/layout.qtpl:34
func (p *BasePage) Body() string {
//line tpl/layout.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:34
	p.WriteBody(qb422016)
//line tpl/layout.qtpl:34
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:34
	return qs422016
//line tpl/layout.qtpl:34
}

//line tpl/layout.qtpl:35
func (p *BasePage) StreamCSS(qw422016 *qt422016.Writer) {
//line tpl/layout.qtpl:35
}

//line tpl/layout.qtpl:35
func (p *BasePage) WriteCSS(qq422016 qtio422016.Writer) {
//line tpl/layout.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:35
	p.StreamCSS(qw422016)
//line tpl/layout.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:35
}

//line tpl/layout.qtpl:35
func (p *BasePage) CSS() string {
//line tpl/layout.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:35
	p.WriteCSS(qb422016)
//line tpl/layout.qtpl:35
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:35
	return qs422016
//line tpl/layout.qtpl:35
}

//line tpl/layout.qtpl:36
func (p *BasePage) StreamJS(qw422016 *qt422016.Writer) {
//line tpl/layout.qtpl:36
}

//line tpl/layout.qtpl:36
func (p *BasePage) WriteJS(qq422016 qtio422016.Writer) {
//line tpl/layout.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/layout.qtpl:36
	p.StreamJS(qw422016)
//line tpl/layout.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line tpl/layout.qtpl:36
}

//line tpl/layout.qtpl:36
func (p *BasePage) JS() string {
//line tpl/layout.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/layout.qtpl:36
	p.WriteJS(qb422016)
//line tpl/layout.qtpl:36
	qs422016 := string(qb422016.B)
//line tpl/layout.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/layout.qtpl:36
	return qs422016
//line tpl/layout.qtpl:36
}
