// Code generated by qtc from "login.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line tpl/login.qtpl:1
package tpl

//line tpl/login.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line tpl/login.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line tpl/login.qtpl:2
type LoginPage struct {
	BasePage
}

//line tpl/login.qtpl:7
func (p *LoginPage) StreamTitle(qw422016 *qt422016.Writer) {
//line tpl/login.qtpl:7
	qw422016.N().S(`
	This is the main page
`)
//line tpl/login.qtpl:9
}

//line tpl/login.qtpl:9
func (p *LoginPage) WriteTitle(qq422016 qtio422016.Writer) {
//line tpl/login.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/login.qtpl:9
	p.StreamTitle(qw422016)
//line tpl/login.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line tpl/login.qtpl:9
}

//line tpl/login.qtpl:9
func (p *LoginPage) Title() string {
//line tpl/login.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/login.qtpl:9
	p.WriteTitle(qb422016)
//line tpl/login.qtpl:9
	qs422016 := string(qb422016.B)
//line tpl/login.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/login.qtpl:9
	return qs422016
//line tpl/login.qtpl:9
}

//line tpl/login.qtpl:12
func (p *LoginPage) StreamBody(qw422016 *qt422016.Writer) {
//line tpl/login.qtpl:12
	qw422016.N().S(`
	<h1>Авторизация</h1>
	<div>
		<div>
		    <form id="form">
                <div>
                    <label for="email">E-Mail:</label>
                    <input type="email" id="email" required/>
                </div>
                <div>
                    <label for="password">Пароль:</label>
                    <input type="password" id="password" required/>
                </div>
                <div id="error"></div>
                <div>
                    <button type="submit" id="button">Войти в систему</button>
                </div>
		    </form>
		</div>
	</div>
`)
//line tpl/login.qtpl:32
}

//line tpl/login.qtpl:32
func (p *LoginPage) WriteBody(qq422016 qtio422016.Writer) {
//line tpl/login.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/login.qtpl:32
	p.StreamBody(qw422016)
//line tpl/login.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line tpl/login.qtpl:32
}

//line tpl/login.qtpl:32
func (p *LoginPage) Body() string {
//line tpl/login.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/login.qtpl:32
	p.WriteBody(qb422016)
//line tpl/login.qtpl:32
	qs422016 := string(qb422016.B)
//line tpl/login.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/login.qtpl:32
	return qs422016
//line tpl/login.qtpl:32
}

//line tpl/login.qtpl:34
func (p *LoginPage) StreamJS(qw422016 *qt422016.Writer) {
//line tpl/login.qtpl:34
	qw422016.N().S(`
<script>`)
//line tpl/login.qtpl:35
	qw422016.N().S(`(() => {
    const
        f = {
            email: gid('email'),
            password: gid('password'),
        },
        button = gid('button'),
        error = gid('error');

    const _getValues = () => Object
        .keys(f)
        .reduce((o, v) => {
            o[v] = f[v].value;
            return o;
        }, Object.create(null));

    const _setError = (s) => error.textContent = s;

    const _setDisabled = (d) => {
        setDisabled(d,
            ...Object.values(f),
            button);
    };

    gid('form').addEventListener('submit', async (event) => {
        event.preventDefault();
        _setError('');
        _setDisabled(true);
        try {
            await api.post('/api/login', _getValues());
            // redirect();
        } catch (err) {
            _setError(err.message);
            _setDisabled(false);
        }
    });
})();`)
//line tpl/login.qtpl:35
	qw422016.N().S(`</script>
`)
//line tpl/login.qtpl:36
}

//line tpl/login.qtpl:36
func (p *LoginPage) WriteJS(qq422016 qtio422016.Writer) {
//line tpl/login.qtpl:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/login.qtpl:36
	p.StreamJS(qw422016)
//line tpl/login.qtpl:36
	qt422016.ReleaseWriter(qw422016)
//line tpl/login.qtpl:36
}

//line tpl/login.qtpl:36
func (p *LoginPage) JS() string {
//line tpl/login.qtpl:36
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/login.qtpl:36
	p.WriteJS(qb422016)
//line tpl/login.qtpl:36
	qs422016 := string(qb422016.B)
//line tpl/login.qtpl:36
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/login.qtpl:36
	return qs422016
//line tpl/login.qtpl:36
}

//line tpl/login.qtpl:38
func (p *LoginPage) StreamCSS(qw422016 *qt422016.Writer) {
//line tpl/login.qtpl:38
	qw422016.N().S(`
<style>`)
//line tpl/login.qtpl:39
	qw422016.N().S(`</style>
`)
//line tpl/login.qtpl:40
}

//line tpl/login.qtpl:40
func (p *LoginPage) WriteCSS(qq422016 qtio422016.Writer) {
//line tpl/login.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line tpl/login.qtpl:40
	p.StreamCSS(qw422016)
//line tpl/login.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line tpl/login.qtpl:40
}

//line tpl/login.qtpl:40
func (p *LoginPage) CSS() string {
//line tpl/login.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line tpl/login.qtpl:40
	p.WriteCSS(qb422016)
//line tpl/login.qtpl:40
	qs422016 := string(qb422016.B)
//line tpl/login.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line tpl/login.qtpl:40
	return qs422016
//line tpl/login.qtpl:40
}
